Music.Web/Models/AlbumFromBandModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Signum.Test;
using Signum.Entities;
using Signum.Test.Environment;

namespace Music.Web
{
    public class AlbumFromBandModel : ModelEntity
    {
        public AlbumFromBandModel()
        { 
        }

        public AlbumFromBandModel(Lite<BandDN> band)
        {
            Band = band;
        }

        Lite<BandDN> band;
        [NotNullValidator]
        public Lite<BandDN> Band
        {
            get { return band; }
            set { Set(ref band, value, () => Band); }
        }

        string name;
        [StringLengthValidator(Min=3, AllowNulls=false)]
        public string Name
        {
            get { return name; }
            set { Set(ref name, value, () => Name); }
        }

        int year;
        [NumberBetweenValidatorAttribute(1000,Int32.MaxValue)]
        public int Year
        {
            get { return year; }
            set { Set(ref year, value, () => Year); }
        }

        LabelDN label;
        [NotNullValidator]
        public LabelDN Label
        {
            get { return label; }
            set { Set(ref label, value, () => Label); }
        }
    }
}

Music.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Signum.Entities.Authorization;
using Signum.Engine.Dashboard;
using Signum.Web.Dashboard;
using Signum.Utilities;
using Signum.Engine;
using Signum.Web;

namespace Music.Web
{
    [AuthenticationRequired(false)]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (UserEntity.Current == null)
                return View();

            var panel = DashboardLogic.GetHomePageDashboard();
            if (panel != null)
                return View(DashboardClient.ViewPrefix.FormatWith("Dashboard"), panel);
            else
                return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Music.Web/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI;
using Signum.Test;
using Signum.Web.Operations;
using Signum.Engine;
using Signum.Entities;
using Signum.Engine.Operations;
using Signum.Engine.Basics;
using Signum.Utilities;
using Signum.Web;
using Signum.Test.Environment;
using Music.Test;

namespace Music.Web
{
    public class MusicController : Controller
    {
        public ViewResult AlbumStrip()
        {
            return this.NormalPage(Database.Retrieve<AlbumEntity>(1), new NavigateOptions { PartialViewName = "AlbumStrip" });
        }

        public ViewResult BandStrip()
        {
            return this.NormalPage(Database.Retrieve<BandEntity>(1), new NavigateOptions { PartialViewName = "BandStrip" });
        }

        public ViewResult BandDetail()
        {
            return this.NormalPage(Database.Retrieve<BandEntity>(1), new NavigateOptions { PartialViewName = "BandDetail" });
        }

        public ViewResult BandRepeater() 
        {
            return this.NormalPage(Database.Retrieve<BandEntity>(1), new NavigateOptions { PartialViewName = "BandRepeater" });
        }

        public ViewResult BandTabRepeater()
        {
            return this.NormalPage(Database.Retrieve<BandEntity>(1), new NavigateOptions { PartialViewName = "BandTabRepeater" });
        }

        [HttpPost]
        public ActionResult CreateAlbumFromBandModel()
        {
            AlbumFromBandModel model = new AlbumFromBandModel();

            return this.PopupView(model, new PopupViewOptions(this.Prefix()));
        }

        [HttpPost]
        public ActionResult CreateAlbumFromBandExecute()
        {
            string modelPrefix = Request["modelPrefix"];

            var model = this.ExtractEntity<AlbumFromBandModel>(modelPrefix)
                .ApplyChanges(this, modelPrefix).Value;

            AlbumEntity newAlbum = this.ExtractLite<BandEntity>().ConstructFromLite(AlbumOperation.CreateAlbumFromBand,
                model.Name, model.Year, model.Label);

            return OperationClient.DefaultConstructResult(this, newAlbum);
        }

        [HttpPost]
        public ActionResult CreateGreatestHitsAlbum()
        {
            var sourceAlbums = this.ParseLiteKeys<AlbumEntity>();
            
            var newAlbum = OperationLogic.ConstructFromMany(sourceAlbums, AlbumOperation.CreateGreatestHitsAlbum);

            return OperationClient.DefaultConstructResult(this, newAlbum);
        }

        [HttpPost]
        public ActionResult Clone()
        {
            var album = this.ExtractLite<AlbumEntity>();

            AlbumEntity newAlbum = album.ConstructFromLite(AlbumOperation.Clone);
            newAlbum.Name = this.ParseValue<string>("newName");

            return OperationClient.DefaultConstructResult(this, newAlbum); 
        }
    }
}

Music.Web/Views/Home/Index.cshtml
@{
    this.ViewBag.Title = "Music Test Project";
}

<div class="container">
    <br />
    <div class="jumbotron">
        <h1>Music Test Project!</h1>
        <p>Small application for testing purposes. If you're looking for something cool, Southwind application is fancier.</p>
    </div>
</div>

<footer class="navbar navbar-fixed-bottom">
    <div id="footerContainer">
        Powered by <a href="http://signumframework.com/">Signum Framework</a>
    </div>
</footer>

Music.Web/Views/Music/AlbumFromBandModel.cshtml
@using Music.Test

@using (var e = Html.TypeContext<AlbumFromBandModel>()) 
{
	@Html.ValueLine(e, f => f.Name);
	@Html.ValueLine(e, f => f.Year);
	@Html.EntityLine(e, f => f.Label);
}

Music.Web/Views/Music/AlbumStrip.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<AlbumEntity>()) 
{
	@Html.ValueLine(e, f => f.Name)
	@Html.ValueLine(e, f => f.Year)
	@Html.EntityLine(e, f => f.Author)
	@Html.EntityStrip(e, f => f.Songs, s=>s.Vertical = true)
    @Html.EntityLine(e, f => f.BonusTrack)
    @Html.EntityCombo(e, f => f.Label)
}

Music.Web/Views/Music/AmericanMusicAward.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<AmericanMusicAwardEntity>()) 
{
	@Html.ValueLine(e, f => f.Year);
	@Html.ValueLine(e, f => f.Category);
	@Html.ValueLine(e, f => f.Result);
}

Music.Web/Views/Music/Artist.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<ArtistEntity>()) 
{
	@Html.ValueLine(e, f => f.Name)
	@Html.ValueLine(e, f => f.Dead)
	@Html.ValueLine(e, f => f.Sex)
	@Html.ValueLine(e, f => f.IsMale)
	@Html.EntityLine(e, f => f.LastAward)
	@Html.EntityList(e, f => f.Friends)
}

Music.Web/Views/Music/Band.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<BandEntity>()) 
{
	@Html.ValueLine(e, f => f.Name);
	@Html.EntityList(e, f => f.Members);
    @Html.EntityLine(e, f => f.LastAward);
    @Html.EntityList(e, f => f.OtherAwards);
}

Music.Web/Views/Music/BandDetail.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<BandEntity>())
{
    @Html.ValueLine(e, f => f.Name);
    <fieldset>
        <legend>@Html.PropertyNiceName(() => e.Value.Members)</legend>
        <div class="row">
            <div class="col-sm-6">@Html.EntityListDetail(e, f => f.Members, eld => { eld.DetailDiv = e.Compose("CurrentMember"); eld.FormGroupStyle = FormGroupStyle.None; })</div>
            <div class="col-sm-6" id="@e.Compose("CurrentMember")"></div>
        </div>
    </fieldset>
    
      
    @Html.EntityDetail(e, f => f.LastAward)
    <fieldset>
        <legend>@Html.PropertyNiceName(() => e.Value.OtherAwards)</legend>
        <div class="row">
            <div class="col-sm-6">@Html.EntityListDetail(e, f => f.OtherAwards, eld => { eld.DetailDiv = e.Compose("CurrentAward"); eld.FormGroupStyle = FormGroupStyle.None; })</div>
            <div class="col-sm-6" id="@e.Compose("CurrentAward")"></div>
        </div>
    </fieldset>
    
  
}

Music.Web/Views/Music/BandRepeater.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<BandEntity>()) 
{
	@Html.ValueLine(e, f => f.Name);
	@Html.EntityRepeater(e, f => f.Members, er => { er.Find = true; er.Move = true; });
    @Html.EntityLine(e, f => f.LastAward);
    @Html.EntityRepeater(e, f => f.OtherAwards);
}

Music.Web/Views/Music/BandStrip.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<BandEntity>()) 
{
	@Html.ValueLine(e, f => f.Name);
	@Html.EntityStrip(e, f => f.Members, es => { es.Find = true; es.Move = true; es.Vertical = true; es.Create = true; es.Navigate = true; es.View = true; });
    @Html.EntityLine(e, f => f.LastAward);
    @Html.EntityStrip(e, f => f.OtherAwards, es => { es.Create = true; });
}

Music.Web/Views/Music/BandTabRepeater.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<BandEntity>()) 
{
	@Html.ValueLine(e, f => f.Name);
	@Html.EntityTabRepeater(e, f => f.Members, er => { er.Find = true; er.Move = true; });
    @Html.EntityLine(e, f => f.LastAward);
    @Html.EntityTabRepeater(e, f => f.OtherAwards);
}

Music.Web/Views/Music/GrammyAward.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<GrammyAwardEntity>()) 
{
	@Html.ValueLine(e, f => f.Year);
	@Html.ValueLine(e, f => f.Category);
	@Html.ValueLine(e, f => f.Result);
}

Music.Web/Views/Music/Label.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<LabelEntity>()) 
{
	@Html.ValueLine(e, f => f.Name)
    @Html.EntityCombo(e, f => f.Owner)
}

Music.Web/Views/Music/NoteWithDate.cshtml
@using Signum.Test.Environment

@using (var nc = Html.TypeContext<NoteWithDateEntity>()) 
{
    @Html.ValueLine(nc, n => n.Mixin<CorruptMixin>().Corrupt)
	@Html.EntityLine(nc, n => n.Target, el => el.ReadOnly = true)
    @Html.ValueLine(nc, n => n.Text, vl => vl.ValueLineType = ValueLineType.TextArea)
	@Html.ValueLine(nc, n => n.CreationTime)
}

Music.Web/Views/Music/PersonalAward.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<PersonalAwardEntity>()) 
{
	@Html.ValueLine(e, f => f.Year);
	@Html.ValueLine(e, f => f.Category);
	@Html.ValueLine(e, f => f.Result);
}

Music.Web/Views/Music/Song.cshtml
@using Signum.Test.Environment

@using (var e = Html.TypeContext<SongEntity>()) 
{
	@Html.ValueLine(e, f => f.Name);
}

Music.Web/Views/Shared/LogOnUserControl.cshtml
@if (Request.IsAuthenticated)
{
    @:Welcome <b>@Html.Encode(Page.User.Identity.Name)</b>
    @:[ @Html.ActionLink("Log Off", "LogOff", "Account") ]
}
else
{ 
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

Music.Web/Views/Shared/Menu.cshtml
@using Signum.Test.Environment
@using Signum.Entities.Dashboard
@using Signum.Entities.Authorization

@Html.WebMenu( 
new WebMenuItem 
{ 
    Text="Music Items", 
    Children = 
    {
        new WebMenuItem { Link = new FindOptions(typeof(AlbumEntity)) },
        new WebMenuItem { Link = new FindOptions(typeof(ArtistEntity)) },
        new WebMenuItem { Link = new FindOptions(typeof(BandEntity)) },
        new WebMenuItem { Link = new FindOptions(typeof(LabelEntity)) },
        new WebMenuItem { Link = new FindOptions(typeof(GrammyAwardEntity)) },
        new WebMenuItem { Link = new FindOptions(typeof(NoteWithDateEntity)) },
        new WebMenuItem { Link = new FindOptions(typeof(IAuthorEntity)) },
    },
},
new WebMenuItem
{
    Text = "Others",
    Children = 
    {
        new WebMenuItem { Text = "Band - Details", Link = Url.Action("BandDetail", "Music") },
        new WebMenuItem { Text = "Band - Repeater", Link = Url.Action("BandRepeater", "Music") },
        new WebMenuItem { Text = "Band - TabRepeater", Link = Url.Action("BandTabRepeater", "Music") },
        new WebMenuItem { Text = "Band - Strip", Link = Url.Action("BandStrip", "Music") },
        new WebMenuItem { Text = "Album - Strip", Link = Url.Action("AlbumStrip", "Music") },
    }
},
new WebMenuItem
{
    Text = "Auth",
    Children = 
    {
        new WebMenuItem { Link = new FindOptions(typeof(UserEntity)) },
        new WebMenuItem { Link = new FindOptions(typeof(RoleEntity)) },
    }
},
new WebMenuItem { Link = new FindOptions(typeof(DashboardEntity)) }
)

Music.Web/Views/Shared/_Layout.cshtml
@using Signum.Web.Auth
@using Signum.Web.Combine
@using Signum.Entities.Authorization
@using Signum.Engine.Authorization
@using Music.Web

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @Html.ScriptCss(
        "~/Libs/bootstrap/css/bootstrap.css",
        "~/Libs/bootstrap/css/bootstrap-theme.css",
        "~/Libs/bootstrap-datepicker/css/datepicker3.css",
        "~/Libs/bootstrap-timepicker/css/bootstrap-timepicker.css",

        "~/Signum/Content/Lines.css",
        "~/Signum/Content/NormalPage.css",
        "~/Signum/Content/Notify.css",
        "~/Signum/Content/Search.css",
        "~/Signum/Content/Widgets.css",
        "~/Content/music.css"
        )

    @Html.ScriptsJs(
        "~/Libs/promise-0.1.1.js",
        "~/Libs/jquery-1.11.0.js",
        "~/Libs/bootstrap/js/bootstrap.js",
        "~/Libs/bootstrap-datepicker/js/bootstrap-datepicker.js",
        "~/Libs/bootstrap-timepicker/js/bootstrap-timepicker.js",
        "~/Libs/bootstrap-typeahead/bootstrap3-typeahead.js",
        "~/Libs/require.js")
    <script>
        require.config({
            baseUrl: '@Url.Content("~/Scripts")',
            paths: {
                "Framework/Signum.Web": "..",
                "Extensions/Signum.Web.Extensions": "..",

                "d3": "../Libs/d3.v3.min",
                "colorbrewer": "../Libs/colorbrewer",
                "ChartUtils": "../Chart/Scripts/ChartUtils",
            },
            shim: {
                d3: { exports: 'd3' },
                colorbrewer: { exports: 'colorbrewer' },
                ChartUtils: { exports: 'ChartUtils' }
            },
            urlArgs: "v=@ScriptHtmlHelper.Manager.Version"
        });
    </script>

    @Html.ScriptsJs("~/Signum/resources/" + System.Globalization.CultureInfo.CurrentCulture.Name + ".js")
    @Html.ScriptsJs("~/Signum/calendarResources/" + System.Globalization.CultureInfo.CurrentCulture.Name + ".js")
    @Html.ScriptsJs("~/Signum/urls/signumCommon.js")
    @Html.ScriptsJs("~/Signum/Scripts/SF.js", "~/Signum/Scripts/SF.UI.js")

    @if (IsSectionDefined("head"))
    {
        @RenderSection("head")
    }
</head>

<body>

    <header class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @(Html.ActionLink<HomeController>("Music", c => c.Index(), new { @class = "navbar-brand" }))
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (UserEntity.Current != null)
                    {
                        Html.RenderPartial("Menu");
                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @{ Html.RenderPartial(AuthClient.LoginUserControlView);}
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>